[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dataframe"
version = "0.1.0"
authors = [
    { name = "Frantz Maerten", email = "fmaerten@gmail.com" },
]
description = "Python binding of Dataframe"